"""Emit ds4's GSQ-RCO grid tables from ggml's ggml-common.h (MIT).

usage: python3 tools/gen_iq_tables.py PATH/TO/ggml-common.h
Writes ds4_iq_tables.h (C) and metal/iq_tables.metal (Metal constant memory) at the repo root."""
import pathlib
import re
import sys

UPSTREAM = "ggml-org/llama.cpp@931351ea50dfdd3ee249606f655eef2e9a629daf ggml/src/ggml-common.h"
NOTICE = ("Generated by tools/gen_iq_tables.py from %s. Do not edit.\n"
          " * Copyright (c) 2023-2026 The ggml authors. MIT License." % UPSTREAM)
# (C type, Metal type, name, entries, values per line)
TABLES = [("uint64_t", "ulong", "iq2xs_grid", 512, 4), ("uint64_t", "ulong", "iq2s_grid", 1024, 4),
          ("uint32_t", "uint", "iq3xxs_grid", 256, 8), ("uint32_t", "uint", "iq3s_grid", 512, 8),
          ("int8_t", "char", "kvalues_iq4nl", 16, 16)]
ROOT = pathlib.Path(__file__).resolve().parent.parent


def table_values(src, ctype, name, n):
    m = re.search(r"GGML_TABLE_BEGIN\(%s,\s*%s,\s*%d\)(.*?)GGML_TABLE_END\(\)" % (ctype, name, n), src, re.S)
    if not m:
        raise SystemExit("table %s not found" % name)
    vals = re.findall(r"-?0x[0-9a-fA-F]+|-?\d+", m.group(1))
    if len(vals) != n:
        raise SystemExit("table %s: %d values, want %d" % (name, len(vals), n))
    return [v + ("ULL" if ctype == "uint64_t" else "u" if ctype == "uint32_t" else "") for v in vals]


def body(vals, per_line):
    return "\n".join("    " + ", ".join(vals[i:i + per_line]) + "," for i in range(0, len(vals), per_line))


def main(argv):
    src = pathlib.Path(argv[1]).read_text()
    c = ["/* %s */\n#pragma once\n#include <stdint.h>\n" % NOTICE]
    metal = ["/* %s */\n" % NOTICE]
    for ctype, mtype, name, n, per in TABLES:
        vals = table_values(src, ctype, name, n)
        c.append("static const %s %s[%d] = {\n%s\n};\n" % (ctype, name, n, body(vals, per)))
        mvals = [v[:-3] if v.endswith("ULL") else v[:-1] if v.endswith("u") else v for v in vals]
        metal.append("static constant %s ds4_metal_%s[%d] = {\n%s\n};\n" % (mtype, name, n, body(mvals, per)))
    (ROOT / "ds4_iq_tables.h").write_text("\n".join(c))
    (ROOT / "metal" / "iq_tables.metal").write_text("\n".join(metal))


if __name__ == "__main__":
    main(sys.argv)
