"""Fixtures for ds4's quant row tests: two real blocks per type from a GGUF, with the values ggml's
reference dequantizers give (gguf-py quants.dequantize; Q2_0 from ggml's dequantize_row_q2_0).

usage: VENV_PYTHON tools/gen_quant_fixtures.py ISTA_SHARD1.gguf > tests/quant_fixtures.h"""
import hashlib
import importlib.metadata
import pathlib
import sys

import numpy as np
import gguf

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import gguf_lite  # noqa: E402

TYPES = [13, 14, 16, 17, 18, 20, 21, 22, 23, 42]


def q2_0_ref(raw):
    """ggml-quants.c dequantize_row_q2_0 @931351ea: y = ((q & 3) - 1) * d, four weights per byte."""
    out = []
    for i in range(0, len(raw), 18):
        d = np.frombuffer(raw[i:i + 2], dtype=np.float16)[0].astype(np.float32)
        qs = np.frombuffer(raw[i + 2:i + 18], dtype=np.uint8)
        q = np.stack([(qs >> (2 * k)) & 3 for k in range(4)], axis=1).reshape(-1).astype(np.int32)
        out.append((q - 1).astype(np.float32) * d)
    return np.concatenate(out)


def blocks(r, f, ttype):
    t = next(t for t in r.tensors if t["type"] == ttype)
    elems, size = gguf_lite.BLOCK[ttype]
    row_bytes = t["dims"][0] // elems * size
    rows = t["nbytes"] // row_bytes
    picks = [t["abs"], t["abs"] + (rows // 2) * row_bytes + (row_bytes // size // 2) * size]
    raw = b""
    for at in picks:
        f.seek(at)
        raw += f.read(size)
    return t["name"], raw


def main(argv):
    r = gguf_lite.Reader(argv[1])
    with open(argv[1], "rb") as f:
        head = hashlib.sha256(f.read(1 << 20)).hexdigest()[:16]
    print("/* Generated by tools/gen_quant_fixtures.py: two blocks per type from")
    print(" * %s (first MiB sha256 %s)," % (pathlib.Path(argv[1]).name, head))
    print(" * values from gguf-py %s quants.dequantize (Q2_0: ggml dequantize_row_q2_0). */"
          % importlib.metadata.version("gguf"))
    print("typedef struct { uint32_t type, n; const uint8_t *bytes; uint32_t n_bytes; const float *want; } ds4_quant_fixture;")
    entries = []
    with open(argv[1], "rb") as f:
        for ttype in TYPES:
            name, raw = blocks(r, f, ttype)
            want = q2_0_ref(raw) if ttype == 42 else np.asarray(
                gguf.quants.dequantize(np.frombuffer(raw, dtype=np.uint8), gguf.GGMLQuantizationType(ttype)),
                dtype=np.float32).reshape(-1)
            print("/* %s */" % name)
            print("static const uint8_t qf_bytes_%d[] = {%s};" % (ttype, ",".join(str(b) for b in raw)))
            print("static const float qf_want_%d[] = {%s};" % (
                ttype, ",".join("%.9ef" % float(v) for v in want)))
            entries.append("    {%d, %d, qf_bytes_%d, %d, qf_want_%d}," % (ttype, len(want), ttype, len(raw), ttype))
    print("static const ds4_quant_fixture quant_fixtures[] = {\n%s\n};" % "\n".join(entries))


if __name__ == "__main__":
    main(sys.argv)
